Metrics/LineLength:
  Max: 120
  Exclude:
    - app/models/comment.rb
Documentation:
 Enabled: false
Metrics/BlockLength:
 Enabled: true
 Exclude:
    - config/routes.rb
    - config/environments/*.rb
Metrics/AbcSize:
 Enabled: true
 Exclude:
   - app/controllers/api/v1/sessions_controller.rb
   - app/controllers/api/v1/comments_controller.rb
   - app/controllers/api/base_controller.rb
   - app/controllers/admin_panel/clinics_controller.rb
   - app/controllers/admin_panel/day_care_centres_controller.rb
   - app/controllers/admin_panel/boardings_controller.rb
   - app/controllers/admin_panel/grooming_centres_controller.rb
   - app/controllers/admin_panel/trainers_controller.rb
   - app/controllers/admin_panel/vets_controller.rb
   - app/controllers/admin_panel/users_controller.rb
   - app/models/concerns/calendar_validation_concern.rb
   - app/helpers/params_cleaner_helper.rb
   - app/services/api/v1/user_services/social_auth_service.rb
   - app/decorators/admin_panel/vet_decorator.rb
   - lib/query_objects/admin_panel/filter_and_pagination_query.rb
   - app/models/appointment.rb
Metrics/CyclomaticComplexity:
  Enabled: true
  Exclude:
    - app/models/location.rb
Metrics/MethodLength:
  Enabled: true
  Exclude:
    - app/services/api/v1/user_services/social_auth_service.rb
    - app/helpers/params_cleaner_helper.rb
    - app/controllers/api/base_controller.rb
    - app/controllers/admin_panel/clinics_controller.rb
    - app/controllers/admin_panel/day_care_centres_controller.rb
    - app/controllers/admin_panel/boardings_controller.rb
    - app/controllers/admin_panel/grooming_centres_controller.rb
    - app/controllers/admin_panel/trainers_controller.rb
    - app/controllers/admin_panel/vets_controller.rb
    - app/controllers/admin_panel/users_controller.rb
    - app/controllers/admin_panel/service_types_controller.rb
    - lib/query_objects/admin_panel/filter_and_pagination_query.rb
Metrics/ClassLength:
  Enabled: true
  Exclude:
   - lib/query_objects/admin_panel/filter_and_pagination_query.rb
   - app/controllers/admin_panel/vets_controller.rb
   - app/controllers/admin_panel/grooming_centres_controller.rb
   - app/models/pet.rb
   - app/models/appointment.rb
AllCops:
 Excludes:
   - Gemfile
   - bin/yarn
   - config/application.rb
   - config/puma.rb
   - db/schema.rb
   - db/seeds.rb
   - db/migrate/*
   - bin/setup
   - lib/api/v1/*
   - spec/**/*
   - config/initializers/devise.rb
   - app/models/ckeditor/*
Style/FrozenStringLiteralComment:
  Enabled: false
Style/PredicateName:
  Enabled: true
  Exclude:
    - app/models/pet.rb
