Metrics/LineLength:
  Max: 120
Documentation:
 Enabled: false
Metrics/BlockLength:
 Enabled: true
 Exclude:
   - config/routes.rb
   - config/environments/*.rb
Metrics/AbcSize:
 Enabled: true
 Exclude:
   - app/controllers/api/v1/sessions_controller.rb
   - app/controllers/api/base_controller.rb
   - app/helpers/params_cleaner_helper.rb
   - app/services/api/v1/user_services/social_auth_service.rb
Metrics/MethodLength:
  Enabled: true
  Exclude:
    - app/services/api/v1/user_services/social_auth_service.rb
    - app/helpers/params_cleaner_helper.rb
    - app/controllers/api/base_controller.rb
AllCops:
 Excludes:
   - Gemfile
   - bin/yarn
   - config/application.rb
   - config/puma.rb
   - db/schema.rb
   - db/seeds.rb
   - db/migrate/*
   - bin/setup
   - lib/api/v1/*
   - spec/**/*
   - config/initializers/devise.rb
Style/FrozenStringLiteralComment:
  Enabled: false
Style/PredicateName:
  Enabled: true
  Exclude:
    - app/models/pet.rb
